-- CREATE DATABASE PROYECTO_FINAL_MESA_4
-- USE PROYECTO_FINAL_MESA_4


-- CREATE TABLE TBL_PERSONA_DETALLE
-- (
-- 	ID_PERSONA_DETALLE	INT				PRIMARY KEY,
-- 	NOMBRE_DETALLE		VARCHAR(20)		NOT NULL,
-- 	APELLIDO_DETALLE	VARCHAR(20)		NOT NULL,
-- 	CEDULA_DETALLE		CHAR(11)		NOT NULL,
-- 	TELEFONO_DETALLE	CHAR(10)		NOT NULL,
-- 	CORREO_DETALLE		VARCHAR(30)		NOT NULL,
-- 	FECHA_NAC_EMPLEADO	DATETIME		NOT NULL,
-- 	FECHA_REGISTRO		DATE			NOT NULL

-- )


-- CREATE TABLE TBL_SEGURO
-- (
-- 	ID_SEGURO		INT				PRIMARY KEY,
-- 	NOMBRE_SEGURO	VARCHAR(20)		NOT NULL,
-- 	ASEGURADORA		VARCHAR(25)		NOT NULL

-- )


-- CREATE TABLE TBL_EDIFICIO
-- (
-- 	ID_EDIFICIO		INT				PRIMARY KEY,
-- 	NOMBRE_EDIFICIO	VARCHAR(25)		NOT NULL

-- )


-- CREATE TABLE TBL_CONSULTORIO
-- (
-- 	ID_CONSULTORIO		INT			PRIMARY KEY,
-- 	NUMERO_CONSULTORIO	VARCHAR(3)	NOT NULL,
-- 	CAPACIDAD_PERSONAS	INT			NOT NULL,
-- 	ID_EDIFICIO			INT	FOREIGN KEY REFERENCES TBL_EDIFICIO(ID_EDIFICIO)					NOT NULL

-- )


-- CREATE TABLE TBL_ROL
-- (
-- 	ID_ROL		INT			PRIMARY KEY,
-- 	NOMBRE_ROL	VARCHAR(25)	NOT NULL

-- )


-- CREATE TABLE TBL_ESTADO
-- (
-- 	ID_ESTADO		INT	PRIMARY KEY,
-- 	NOMBRE_ESTADO	VARCHAR(25)	NOT NULL

-- )


-- CREATE TABLE TBL_EMPLEADO
-- (
-- 	ID_EMPLEADO			INT	PRIMARY KEY,
-- 	ID_PERSONA_DETALLE	INT	FOREIGN KEY REFERENCES TBL_PERSONA_DETALLE(ID_PERSONA_DETALLE) NOT NULL,
-- 	ID_ROL				INT	FOREIGN KEY REFERENCES TBL_ROL(ID_ROL) NOT NULL,
-- 	ID_ESTADO			INT	FOREIGN KEY REFERENCES TBL_ESTADO(ID_ESTADO) NOT NULL

-- )


-- CREATE TABLE TBL_ODONTOLOGO
-- (
-- 	ID_ODONTOLOGO	INT	PRIMARY KEY	NOT NULL,
-- 	ID_EMPLEADO		INT	FOREIGN KEY REFERENCES TBL_EMPLEADO(ID_EMPLEADO) NOT NULL,
-- 	ID_CONSULTORIO	INT	FOREIGN KEY REFERENCES TBL_CONSULTORIO(ID_CONSULTORIO)	NOT NULL,

-- )


-- CREATE TABLE TBL_SECRETARIA
-- (
-- 	ID_SECRETARIA	INT	PRIMARY KEY,
-- 	ID_EMPLEADO		INT	FOREIGN KEY REFERENCES TBL_EMPLEADO(ID_EMPLEADO) NOT NULL,
-- 	ID_ODONTOLOGO	INT	FOREIGN KEY REFERENCES TBL_ODONTOLOGO(ID_ODONTOLOGO)	NOT NULL,

-- )


-- CREATE TABLE TBL_PACIENTE
-- (
-- 	ID_PACIENTE			INT	PRIMARY KEY,
-- 	ID_PERSONA_DETALLE	INT FOREIGN KEY REFERENCES TBL_PERSONA_DETALLE(ID_PERSONA_DETALLE)	NOT NULL,
-- 	ID_EMPLEADO			INT	FOREIGN KEY REFERENCES TBL_EMPLEADO	(ID_EMPLEADO) NOT NULL,
-- 	ID_ESTADO			INT FOREIGN KEY REFERENCES TBL_ESTADO(ID_ESTADO)	NOT NULL,
-- 	ID_ODONTOLOGO		INT	FOREIGN KEY REFERENCES TBL_ODONTOLOGO(ID_ODONTOLOGO) NOT NULL,

-- )


-- CREATE TABLE TBL_MATERIAL
-- (
-- ID_MATERIAL		INT	PRIMARY KEY,
-- NOMBRE_MATERIAL	VARCHAR(30)	NOT NULL

-- )


-- CREATE TABLE TBL_PROVINCIA
-- (
-- 	ID_PROVINCIA		INT	PRIMARY KEY,
-- 	NOMBRE_PROVINCIA	VARCHAR(30)	NOT NULL

-- )


-- CREATE TABLE TBL_MUNICIPIO
-- (
-- 	ID_MUNICIPIO		INT	PRIMARY KEY,
-- 	ID_PROVINCIA		INT	FOREIGN KEY REFERENCES TBL_PROVINCIA(ID_PROVINCIA) NOT NULL,
-- 	NOMBRE_MUNICIPIO	VARCHAR(20)	NOT NULL

-- )


-- CREATE TABLE TBL_SECTOR
-- (
-- 	ID_SECTOR		INT	PRIMARY KEY,
-- 	ID_MUNICIPIO	INT	FOREIGN KEY REFERENCES TBL_MUNICIPIO(ID_MUNICIPIO) NOT NULL,
-- 	NOMBRE_SECTOR	VARCHAR(25)	NOT NULL

-- )


-- CREATE TABLE TBL_SUCURSAL
-- (
-- 	ID_SUCURSAL		INT	PRIMARY KEY,
-- 	ID_SECTOR		INT	FOREIGN KEY REFERENCES TBL_SECTOR(ID_SECTOR) NOT NULL,
-- 	NOMBRE_SUCURSAL	VARCHAR(20)	NOT NULL,
-- 	RNC				CHAR(9)	NOT NULL,

-- )


-- CREATE TABLE TBL_CITA
-- (
-- 	ID_CITA			INT	PRIMARY KEY,
-- 	ID_PACIENTE		INT	FOREIGN KEY REFERENCES TBL_PACIENTE(ID_PACIENTE)	NOT NULL,
-- 	ID_ODONTOLOGO	INT	FOREIGN KEY REFERENCES TBL_ODONTOLOGO(ID_ODONTOLOGO)	NOT NULL,
-- 	ID_SUCURSAL		INT	FOREIGN KEY REFERENCES TBL_SUCURSAL(ID_SUCURSAL)	NOT NULL,
-- 	FECHA_CITA		DATETIME	NOT NULL

-- )


-- CREATE TABLE TBL_PROVEEDOR
-- (
-- 	ID_PROVEEDOR		INT	PRIMARY KEY,
-- 	NOMBRE_PROVEEDOR	VARCHAR(20)	NOT NULL,
-- 	RNC					CHAR(9)		NOT NULL,
-- 	ID_SECTOR			INT	FOREIGN KEY REFERENCES TBL_SECTOR(ID_SECTOR)	NOT NULL

-- )


-- CREATE TABLE TBL_PROVEEDOR_MATERIAL
-- (
-- 	ID_PROVEEDOR_MATERIAL	INT PRIMARY KEY	NOT NULL,
-- 	ID_PROVEEDOR 			INT	FOREIGN KEY REFERENCES TBL_PROVEEDOR(ID_PROVEEDOR) 	NOT NULL,
-- 	ID_MATERIAL				INT	FOREIGN KEY REFERENCES TBL_MATERIAL(ID_MATERIAL) 	NOT NULL,
-- 	ID_SUCURSAL				INT	FOREIGN KEY REFERENCES TBL_SUCURSAL(ID_SUCURSAL) 	NOT NULL,

-- )


-- CREATE TABLE TBL_EMPLEADO_SUCURSAL
-- (
-- 	ID_EMPLEADO_SUCURSAL	INT		PRIMARY KEY,
-- 	ID_SUCURSAL				INT	FOREIGN KEY REFERENCES TBL_SUCURSAL(ID_SUCURSAL)		NOT NULL,
-- 	ID_EMPLEADO				INT	FOREIGN KEY REFERENCES TBL_EMPLEADO(ID_EMPLEADO)		NOT NULL,
-- 	FECHA_ENTRADA			DATE	NOT NULL,
-- 	FECHA_SALIDA			DATE	NOT NULL,

-- )